import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Alert, Platform } from 'react-native';

export const LANGUAGES = [
  { id: 'en', code: 'en', name: 'English', native: 'English', flag: 'EN' },
  { id: 'kn', code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: 'KN' },
  { id: 'hi', code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: 'HI' },
  { id: 'ta', code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: 'TA' },
  { id: 'te', code: 'te', name: 'Telugu', native: 'తెలుగు', flag: 'TE' },
  { id: 'ml', code: 'ml', name: 'Malayalam', native: 'മലയാളം', flag: 'ML' },
];

export const TRANSLATIONS = {
  en: {
    app_settings: 'App Settings',
    settings_subtitle: 'Preferences, security & system',
    notifications_alerts: 'Notifications & Alerts',
    push_notifications: 'Push Notifications',
    push_sub: 'Appointment reminders & health tips',
    whatsapp_updates: 'WhatsApp Prescription & Bills',
    whatsapp_sub: 'Receive order tracking on WhatsApp',
    sms_alerts: 'SMS Notifications',
    sms_sub: 'Critical OTPs and hospital confirmations',
    security_auth: 'Security & Authentication',
    change_password: 'Change Password',
    change_pass_sub: 'Update your account login password',
    biometric_unlock: 'Biometric & Face ID Unlock',
    biometric_sub: 'Fast biometric authentication',
    regional_display: 'Regional & Display',
    app_language: 'App Language',
    dark_mode: 'Dark Mode Theme',
    dark_mode_sub: 'Switch between light and dark themes',
    data_storage: 'Data & Storage',
    clear_cache: 'Clear App Cache',
    clear_cache_sub: 'Free up temporary cache & images',
    logout_btn: 'Log Out of MediUnify Care',
    app_version: 'MediUnify Healthcare App • v2.4.0 (Build 420)',
    select_language: 'Select App Language',
    cancel: 'Cancel',
    save: 'Save',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    update_password_btn: 'Update Password',
    cache_cleared_title: 'Cache Cleared!',
    cache_cleared_msg: 'Temporary cache and cached assets have been freed successfully.',
    lang_changed_msg: 'App language updated to',
    theme_switched_dark: 'Dark mode activated',
    theme_switched_light: 'Light mode activated',
    nav_home: 'Home',
    nav_search: 'Search',
    nav_ai_bot: 'AI Chat Bot',
    nav_alerts: 'Alerts',
    nav_history: 'History',
    nav_find_doctors: 'Find Doctors',
    nav_lab_tests: 'Lab Tests',
    nav_order_medicine: 'Order Medicine',
    nav_surgeries: 'Surgeries',
    nav_scans_xray: 'Scans & X-Ray',
    nav_more_services: 'More Services',
    nav_login_signup: 'Login / Signup',
    nav_location: 'Location',
    nav_select_location: 'Select Your Location',
    nav_language: 'Language',
    nav_cart: 'Cart',
    profile_title: 'PROFILE',
    guest_user: 'Guest User',
    guest_subtitle: 'Login to access your profile',
    edit_profile: 'Edit Profile',
    quick_access: 'Quick access',
    family_members: 'Family Members',
    health_records: 'Health Records',
    payment_history: 'Payment History',
    settings: 'Settings',
    personal_info: 'Personal Information',
    address: 'Address',
    membership: 'Membership',
    notifications: 'Notifications',
    language: 'Language',
    help_support: 'Help & Support',
    about_app: 'About MediUnify',
    login_sign_in: 'Login / Sign In',
    logout: 'Log Out',
    valid_until: 'Valid until',
    active: 'Active',
    explore_plans: 'Explore Plans',
    done: 'Done',
    lang_updated_title: 'Language Updated',
    lang_updated_desc: 'App language set to',
    my_appointments: 'My Appointments',
    my_tests: 'My Tests',
    my_medicine_orders: 'My Medicine Orders',
    my_medical_records: 'My Medical Records',
    my_online_consultations: 'My Online Consultations',
    my_feedback: 'My Feedback',
    view_update_profile: 'View / Update Profile',
    hero_badge: 'TRUSTED BY PATIENTS ACROSS INDIA',
    refer_earn: 'Refer & Earn ₹250',
    hero_title_navy: 'Your Healthcare.',
    hero_title_teal: 'One Intelligent Platform.',
    hero_subtitle: 'Find doctors, book lab tests, order medicines, access Scans & X-Ray and connect with trusted hospitals — all in one place.',
    search_placeholder: 'Search doctors, clinics, hospitals, tests, medicines...',
    search_btn: 'Search',
    popular_searches: 'Popular:',
    book_appointment: 'Book Appointment',
    order_medicine: 'Order Medicine',
    view_services: 'View Services',
    card_video_consult: 'Video Consultation',
    card_video_desc: 'Connect with expert doctors from the comfort of your home.',
    card_find_doctors: 'Find Doctors Near You',
    card_doctors_desc: 'Confirmed clinic appointments with top verified specialists.',
    card_order_medicines: 'Order Medicines',
    card_medicine_desc: 'Genuine prescription & OTC medicines delivered swiftly.',
    card_lab_tests: 'Lab Tests',
    card_lab_desc: 'Sample pickup from your doorstep with 100% accurate digital reports.',
    card_surgeries: 'Surgeries',
    card_surgeries_desc: 'Zero hassle, insurance assistance & personalized care buddy for surgery.',
    card_scans_xray: 'Scans & X-Ray',
    card_scans_desc: 'High-precision MRI, CT, Ultrasound & X-Ray scans at certified labs.',
    card_home_nursing: 'Home Nursing & Care',
    card_nursing_desc: 'Professional nurses and trained caregivers at your doorstep.',
    card_equipment_rental: 'Equipment Rental',
    card_equipment_desc: 'Hospital beds, oxygen concentrators, wheelchairs & more.',
    card_ayurveda: 'Ayurvedic & Wellness',
    card_ayurveda_desc: 'Traditional Ayurvedic doctors, holistic therapy & panchakarma.',
    card_fertility: 'Fertility & IVF',
    card_fertility_desc: 'Specialized IVF specialists, fertility testing & compassionate care.',
    card_health_insurance: 'Health Insurance',
    card_insurance_desc: 'Cashless hospital claims & comprehensive medical coverage.',
    card_emergency: 'Emergency SOS',
    card_emergency_desc: '24/7 ambulance dispatch & emergency medical helpline.',
    specialties_heading: 'Consult Top Specialists for Any Health Concern',
    specialties_subtitle: 'Private online consultations with verified doctors across 25+ specialities',
    book_in_clinic: 'Book In-Clinic Visit',
    book_now: 'Book Now',
    order_now: 'Order Now',
    view_slots: 'View Slots',
    view_details: 'View Details',
    consult_now: 'Consult Now',
    add_to_cart: 'Add to Cart',
    apply: 'Apply',
    close: 'Close',
    confirm: 'Confirm',
  },
  kn: {
    app_settings: 'ಆ್ಯಪ್ ಸೆಟ್ಟಿಂಗ್ಸ್',
    settings_subtitle: 'ಆದ್ಯತೆಗಳು, ಭದ್ರತೆ ಮತ್ತು ವ್ಯವಸ್ಥೆ',
    notifications_alerts: 'ಸೂಚನೆಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    push_notifications: 'ಪುಶ್ ನೋಟಿಫಿಕೇಶನ್‌ಗಳು',
    push_sub: 'ನೇಮಕಾತಿ ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ಆರೋಗ್ಯ ಸಲಹೆಗಳು',
    whatsapp_updates: 'ವಾಟ್ಸಾಪ್ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ & ಬಿಲ್‌ಗಳು',
    whatsapp_sub: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಆರ್ಡರ್ ಟ್ರ್ಯಾಕಿಂಗ್ ಪಡೆಯಿರಿ',
    sms_alerts: 'SMS ಸಂದೇಶಗಳು',
    sms_sub: 'ಪ್ರಮುಖ OTP ಮತ್ತು ಆಸ್ಪತ್ರೆ ದೃಢೀಕರಣಗಳು',
    security_auth: 'ಭದ್ರತೆ ಮತ್ತು ದೃಢೀಕರಣ',
    change_password: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    change_pass_sub: 'ನಿಮ್ಮ ಖಾತೆಯ ಲಾಗಿನ್ ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ',
    biometric_unlock: 'ಬಯೋಮೆಟ್ರಿಕ್ & ಫೇಸ್ ಐಡಿ ಅನ್‌ಲಾಕ್',
    biometric_sub: 'ವೇಗದ ಬಯೋಮೆಟ್ರಿಕ್ ದೃಢೀಕರಣ',
    regional_display: 'ಪ್ರಾದೇಶಿಕ ಮತ್ತು ಪ್ರದರ್ಶನ',
    app_language: 'ಆ್ಯಪ್ ಭಾಷೆ',
    dark_mode: 'ಡಾರ್ಕ್ ಮೋಡ್ ಥೀಮ್',
    dark_mode_sub: 'ಲೈಟ್ ಮತ್ತು ಡಾರ್ಕ್ ಥೀಮ್ ನಡುವೆ ಬದಲಾಯಿಸಿ',
    data_storage: 'ಡೇಟಾ ಮತ್ತು ಸಂಗ್ರಹಣೆ',
    clear_cache: 'ಆ್ಯಪ್ ಕ್ಯಾಶ್ ತೆರವುಗೊಳಿಸಿ',
    clear_cache_sub: 'ತಾತ್ಕಾಲಿಕ ಸಂಗ್ರಹಣೆ ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
    logout_btn: 'MediUnify ನಿಂದ ಲಾಗ್‌ಔಟ್ ಆಗಿ',
    app_version: 'MediUnify ಆರೋಗ್ಯ ಆ್ಯಪ್ • v2.4.0 (ಕನ್ನಡ)',
    select_language: 'ಆ್ಯಪ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    save: 'ಉಳಿಸಿ',
    current_password: 'ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್',
    new_password: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
    confirm_password: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    update_password_btn: 'ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ',
    cache_cleared_title: 'ಕ್ಯಾಶ್ ತೆರವುಗೊಳಿಸಲಾಗಿದೆ!',
    cache_cleared_msg: 'ತಾತ್ಕಾಲಿಕ ಮೆಮೊರಿ ಯಶಸ್ವಿಯಾಗಿ ತೆರವುಗೊಂಡಿದೆ.',
    lang_changed_msg: 'ಆ್ಯಪ್ ಭಾಷೆ ಕನ್ನಡಕ್ಕೆ ಬದಲಾಯಿಸಲಾಗಿದೆ',
    theme_switched_dark: 'ಡಾರ್ಕ್ ಮೋಡ್ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ',
    theme_switched_light: 'ಲೈಟ್ ಮೋಡ್ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ',
    nav_home: 'ಮುಖಪುಟ',
    nav_search: 'ಹುಡುಕಿ',
    nav_ai_bot: 'AI ಚಾಟ್‌ಬಾಟ್',
    nav_alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    nav_history: 'ಇತಿಹಾಸ',
    nav_find_doctors: 'ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
    nav_lab_tests: 'ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳು',
    nav_order_medicine: 'ಔಷಧಿಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಿ',
    nav_surgeries: 'ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಗಳು',
    nav_scans_xray: 'ಸ್ಕ್ಯಾನ್ ಮತ್ತು ಎಕ್ಸ್-ರೇ',
    nav_more_services: 'ಇನ್ನಷ್ಟು ಸೇವೆಗಳು',
    nav_login_signup: 'ಲಾಗಿನ್ / ಸೈನ್ ಅಪ್',
    nav_location: 'ಸ್ಥಳ',
    nav_select_location: 'ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    nav_language: 'ಭಾಷೆ',
    nav_cart: 'ಕಾರ್ಟ್',
    profile_title: 'ಪ್ರೊಫೈಲ್',
    guest_user: 'ಅತಿಥಿ ಬಳಕೆದಾರ',
    guest_subtitle: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪ್ರವೇಶಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ',
    edit_profile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    quick_access: 'ತ್ವರಿತ ಪ್ರವೇಶ',
    family_members: 'ಕುಟುಂಬದ ಸದಸ್ಯರು',
    health_records: 'ಆರೋಗ್ಯ ದಾಖಲೆಗಳು',
    payment_history: 'ಪಾವತಿ ಇತಿಹಾಸ',
    settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    personal_info: 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    address: 'ವಿಳಾಸ',
    membership: 'ಸದಸ್ಯತ್ವ',
    notifications: 'ಸೂಚನೆಗಳು',
    language: 'ಭಾಷೆ',
    help_support: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    about_app: 'MediUnify ಬಗ್ಗೆ',
    login_sign_in: 'ಲಾಗಿನ್ / ಸೈನ್ ಇನ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    valid_until: 'ಮಾನ್ಯತೆಯ ಕೊನೆ ದಿನಾಂಕ',
    active: 'ಸಕ್ರಿಯ',
    explore_plans: 'ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    done: 'ಮುಗಿದಿದೆ',
    lang_updated_title: 'ಭಾಷೆ ನವೀಕರಿಸಲಾಗಿದೆ',
    lang_updated_desc: 'ಆ್ಯಪ್ ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಲಾಗಿದೆ:',
    my_appointments: 'ನನ್ನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    my_tests: 'ನನ್ನ ಪರೀಕ್ಷೆಗಳು',
    my_medicine_orders: 'ನನ್ನ ಔಷಧಿ ಆರ್ಡರ್‌ಗಳು',
    my_medical_records: 'ನನ್ನ ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು',
    my_online_consultations: 'ನನ್ನ ಆನ್‌ಲೈನ್ ಸಮಾಲೋಚನೆಗಳು',
    my_feedback: 'ನನ್ನ ಪ್ರತಿಕ್ರಿಯೆ',
    view_update_profile: 'ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ / ನವೀಕರಿಸಿ',
    hero_badge: 'ಭಾರತದಾದ್ಯಂತ ರೋಗಿಗಳಿಂದ ವಿಶ್ವಾಸಾರ್ಹ',
    refer_earn: 'ರೆಫರ್ ಮಾಡಿ ₹250 ಗಳಿಸಿ',
    hero_title_navy: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ರಕ್ಷಣೆ.',
    hero_title_teal: 'ಒಂದೇ ಬುದ್ಧಿವಂತ ವೇದಿಕೆ.',
    hero_subtitle: 'ವೈದ್ಯರನ್ನು ಹುಡುಕಿ, ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳನ್ನು ಬುಕ್ ಮಾಡಿ, ಔಷಧಿಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಿ, ಸ್ಕ್ಯಾನ್ ಮತ್ತು ಎಕ್ಸ್-ರೇ ಪಡೆಯಿರಿ — ಎಲ್ಲವೂ ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ.',
    search_placeholder: 'ವೈದ್ಯರು, ಕ್ಲಿನಿಕ್‌ಗಳು, ಆಸ್ಪತ್ರೆಗಳು, ಪರೀಕ್ಷೆಗಳು, ಔಷಧಿಗಳನ್ನು ಹುಡುಕಿ...',
    search_btn: 'ಹುಡುಕಿ',
    popular_searches: 'ಜನಪ್ರಿಯ:',
    book_appointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
    order_medicine: 'ಔಷಧಿಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಿ',
    view_services: 'ಸೇವೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    card_video_consult: 'ವೀಡಿಯೊ ಸಮಾಲೋಚನೆ',
    card_video_desc: 'ನಿಮ್ಮ ಮನೆಯಿಂದಲೇ ತಜ್ಞ ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ.',
    card_find_doctors: 'ನಿಮ್ಮ ಹತ್ತಿರದ ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
    card_doctors_desc: 'ಪರಿಶೀಲಿಸಿದ ತಜ್ಞರೊಂದಿಗೆ ದೃಢೀಕೃತ ಕ್ಲಿನಿಕ್ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು.',
    card_order_medicines: 'ಔಷಧಿಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಿ',
    card_medicine_desc: 'ಅಸಲಿ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಮತ್ತು ಔಷಧಿಗಳು ವೇಗವಾಗಿ ತಲುಪುತ್ತವೆ.',
    card_lab_tests: 'ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳು',
    card_lab_desc: 'ಮನೆಯ ಬಾಗಿಲಲ್ಲೇ ಸ್ಯಾಂಪಲ್ ಸಂಗ್ರಹ ಮತ್ತು ನಿಖರ ಡಿಜಿಟಲ್ ವರದಿಗಳು.',
    card_surgeries: 'ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಗಳು',
    card_surgeries_desc: 'ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಗೆ ವಿಮೆ ಸಹಾಯ ಮತ್ತು ವೈಯಕ್ತಿಕ ಬೆಂಬಲ.',
    card_scans_xray: 'ಸ್ಕ್ಯಾನ್ ಮತ್ತು ಎಕ್ಸ್-ರೇ',
    card_scans_desc: 'ಪ್ರಮಾಣೀಕೃತ ಲ್ಯಾಬ್‌ಗಳಲ್ಲಿ ನಿಖರವಾದ MRI, CT ಮತ್ತು ಅಲ್ಟ್ರಾಸೌಂಡ್ ಸ್ಕ್ಯಾನ್‌ಗಳು.',
    card_home_nursing: 'ಮನೆ ನರ್ಸಿಂಗ್ ಮತ್ತು ಆರೈಕೆ',
    card_nursing_desc: 'ನಿಮ್ಮ ಮನೆಯ ಬಾಗಿಲಲ್ಲಿಯೇ ನುರಿತ ನರ್ಸ್‌ಗಳು ಮತ್ತು ಆರೈಕೆದಾರರು.',
    card_equipment_rental: 'ಉಪಕರಣಗಳ ಬಾಡಿಗೆ',
    card_equipment_desc: 'ಆಸ್ಪತ್ರೆಯ ಹಾಸಿಗೆಗಳು, ಆಕ್ಸಿಜನ್ ಕಾನ್ಸೆಂಟ್ರೇಟರ್‌ಗಳು, ಗಾಲಿಕುರ್ಚಿಗಳು.',
    card_ayurveda: 'ಆಯುರ್ವೇದ ಮತ್ತು ಕ್ಷೇಮ',
    card_ayurveda_desc: 'ಸಾಂಪ್ರದಾಯಿಕ ಆಯುರ್ವೇದ ವೈದ್ಯರು ಮತ್ತು ಪಂಚಕರ್ಮ ಚಿಕಿತ್ಸೆ.',
    card_fertility: 'ಫಲವತ್ತತೆ ಮತ್ತು IVF',
    card_fertility_desc: 'ವಿಶೇಷ IVF ತಜ್ಞರು ಮತ್ತು ಫಲವತ್ತತೆ ಪರೀಕ್ಷೆಗಳು.',
    card_health_insurance: 'ಆರೋಗ್ಯ ವಿಮೆ',
    card_insurance_desc: 'ಕ್ಯಾಶ್‌ಲೆಸ್ ಆಸ್ಪತ್ರೆ ಕ್ಲೈಮ್‌ಗಳು ಮತ್ತು ಸಮಗ್ರ ಕವರೇಜ್.',
    card_emergency: 'ತುರ್ತು SOS',
    card_emergency_desc: '24/7 ಆಂಬ್ಯುಲೆನ್ಸ್ ಮತ್ತು ತುರ್ತು ವೈದ್ಯಕೀಯ ಸಹಾಯ.',
    specialties_heading: 'ಯಾವುದೇ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗೆ ಅಗ್ರ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ',
    specialties_subtitle: '25+ ವಿಶೇಷತೆಗಳಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ವೈದ್ಯರೊಂದಿಗೆ ಖಾಸಗಿ ಸಮಾಲೋಚನೆ',
    book_in_clinic: 'ಕ್ಲಿನಿಕ್ ಭೇಟಿಯನ್ನು ಬುಕ್ ಮಾಡಿ',
    book_now: 'ಈಗ ಬುಕ್ ಮಾಡಿ',
    order_now: 'ಈಗ ಆರ್ಡರ್ ಮಾಡಿ',
    view_slots: 'ಸ್ಲಾಟ್‌ಗಳನ್ನು ನೋಡಿ',
    view_details: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    consult_now: 'ಈಗ ಸಮಾಲೋಚಿಸಿ',
    add_to_cart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    apply: 'ಅನ್ವಯಿಸಿ',
    close: 'ಮುಚ್ಚಿ',
    confirm: 'ದೃಢೀಕರಿಸಿ',
  },
  hi: {
    app_settings: 'ऐप सेटिंग्स',
    settings_subtitle: 'प्राथमिकताएं, सुरक्षा और सिस्टम',
    notifications_alerts: 'सूचनाएं और अलर्ट',
    push_notifications: 'पुश नोटिफिकेशन्स',
    push_sub: 'अपॉइंटमेंट रिमाइंडर और स्वास्थ्य टिप्स',
    whatsapp_updates: 'व्हाट्सएप पर्ची और बिल',
    whatsapp_sub: 'व्हाट्सएप पर ऑर्डर ट्रैकिंग प्राप्त करें',
    sms_alerts: 'एसएमएस अलर्ट',
    sms_sub: 'महत्वपूर्ण ओटीपी और अस्पताल की पुष्टि',
    security_auth: 'सुरक्षा और प्रमाणीकरण',
    change_password: 'पासवर्ड बदलें',
    change_pass_sub: 'अपना खाता लॉगिन पासवर्ड अपडेट करें',
    biometric_unlock: 'बायोमेट्रिक और फेस आईडी अनलॉक',
    biometric_sub: 'त्वरित बायोमेट्रिक प्रमाणीकरण',
    regional_display: 'क्षेत्रीय और डिस्प्ले',
    app_language: 'ऐप की भाषा',
    dark_mode: 'डार्क मोड थीम',
    dark_mode_sub: 'लाइट और डार्क थीम के बीच स्विच करें',
    data_storage: 'डेटा और स्टोरेज',
    clear_cache: 'ऐप कैश साफ़ करें',
    clear_cache_sub: 'अस्थायी कैश और छवियां साफ़ करें',
    logout_btn: 'MediUnify से लॉग आउट करें',
    app_version: 'MediUnify हेल्थकेयर ऐप • v2.4.0 (हिन्दी)',
    select_language: 'ऐप भाषा चुनें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    current_password: 'वर्तमान पासवर्ड',
    new_password: 'नया पासवर्ड',
    confirm_password: 'नए पासवर्ड की पुष्टि करें',
    update_password_btn: 'पासवर्ड अपडेट करें',
    cache_cleared_title: 'कैश साफ़ हो गया!',
    cache_cleared_msg: 'अस्थायी स्टोरेज सफलतापूर्वक साफ़ कर दिया गया है।',
    lang_changed_msg: 'ऐप की भाषा हिन्दी में बदल दी गई है',
    theme_switched_dark: 'डार्क मोड सक्रिय किया गया',
    theme_switched_light: 'लाइट मोड सक्रिय किया गया',
    nav_home: 'होम',
    nav_search: 'खोजें',
    nav_ai_bot: 'एआई चैट बॉट',
    nav_alerts: 'अलर्ट',
    nav_history: 'इतिहास',
    nav_find_doctors: 'डॉक्टर खोजें',
    nav_lab_tests: 'लैब टेस्ट',
    nav_order_medicine: 'दवाइयां मंगवाएं',
    nav_surgeries: 'सर्जरी',
    nav_scans_xray: 'स्कैन और एक्स-रे',
    nav_more_services: 'अधिक सेवाएं',
    nav_login_signup: 'लॉग इन / साइन अप',
    nav_location: 'स्थान',
    nav_select_location: 'अपना स्थान चुनें',
    nav_language: 'भाषा',
    nav_cart: 'कार्ट',
    profile_title: 'प्रोफ़ाइल',
    guest_user: 'अतिथि उपयोगकर्ता',
    guest_subtitle: 'अपनी प्रोफ़ाइल देखने के लिए लॉगिन करें',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    quick_access: 'त्वरित पहुँच',
    family_members: 'परिवार के सदस्य',
    health_records: 'स्वास्थ्य रिकॉर्ड',
    payment_history: 'भुगतान इतिहास',
    settings: 'सेटिंग्स',
    personal_info: 'व्यक्तिगत जानकारी',
    address: 'पता',
    membership: 'सदस्यता',
    notifications: 'सूचनाएं',
    language: 'भाषा',
    help_support: 'सहायता और समर्थन',
    about_app: 'MediUnify के बारे में',
    login_sign_in: 'लॉग इन / साइन इन',
    logout: 'लॉग आउट',
    valid_until: 'मान्य अवधि',
    active: 'सक्रिय',
    explore_plans: 'योजनाएं देखें',
    done: 'पूर्ण',
    lang_updated_title: 'भाषा अपडेट की गई',
    lang_updated_desc: 'ऐप की भाषा सेट की गई:',
    my_appointments: 'मेरे अपॉइंटमेंट्स',
    my_tests: 'मेरे टेस्ट',
    my_medicine_orders: 'मेरे दवा ऑर्डर',
    my_medical_records: 'मेरे मेडिकल रिकॉर्ड्स',
    my_online_consultations: 'मेरी ऑनलाइन सलाह',
    my_feedback: 'मेरी प्रतिक्रिया',
    view_update_profile: 'प्रोफ़ाइल देखें / अपडेट करें',
    hero_badge: 'भारत भर के रोगियों द्वारा विश्वसनीय',
    refer_earn: 'रेफर करें और ₹250 कमाएं',
    hero_title_navy: 'आपकी स्वास्थ्य सेवा।',
    hero_title_teal: 'एक बुद्धिमान मंच।',
    hero_subtitle: 'डॉक्टर खोजें, लैब टेस्ट बुक करें, दवाएं मंगवाएं, स्कैन और एक्स-रे प्राप्त करें — सब कुछ एक ही स्थान पर।',
    search_placeholder: 'डॉक्टर, क्लीनिक, अस्पताल, टेस्ट, दवाएं खोजें...',
    search_btn: 'खोजें',
    popular_searches: 'लोकप्रिय:',
    book_appointment: 'अपॉइंटमेंट बुक करें',
    order_medicine: 'दवाइयां मंगवाएं',
    view_services: 'सेवाएं देखें',
    card_video_consult: 'वीडियो परामर्श',
    card_video_desc: 'घर बैठे विशेषज्ञ डॉक्टरों से जुड़ें।',
    card_find_doctors: 'अपने पास के डॉक्टर खोजें',
    card_doctors_desc: 'शीर्ष सत्यापित विशेषज्ञों के साथ निश्चित क्लीनिक अपॉइंटमेंट।',
    card_order_medicines: 'दवाइयां मंगवाएं',
    card_medicine_desc: 'असली दवाएं तेजी से आपके दरवाजे पर पहुंचाई जाती हैं।',
    card_lab_tests: 'लैब टेस्ट',
    card_lab_desc: 'घर से सैंपल पिकअप और 100% सटीक डिजिटल रिपोर्ट।',
    card_surgeries: 'सर्जरी',
    card_surgeries_desc: 'सर्जरी के लिए परेशानी मुक्त प्रक्रिया, बीमा सहायता और केयर बडी।',
    card_scans_xray: 'स्कैन और एक्स-रे',
    card_scans_desc: 'प्रमाणित लैब में उच्च-सटीक एमआरआई, सीटी, अल्ट्रासाउंड और एक्स-रे।',
    card_home_nursing: 'होम नर्सिंग और देखभाल',
    card_nursing_desc: 'प्रशिक्षित नर्सें और देखभालकर्ता आपके घर पर उपलब्ध।',
    card_equipment_rental: 'उपकरण किराया',
    card_equipment_desc: 'अस्पताल के बिस्तर, ऑक्सीजन कंसंट्रेटर, व्हीलचेयर।',
    card_ayurveda: 'आयुर्वेद और कल्याण',
    card_ayurveda_desc: 'पारंपरिक आयुर्वेदिक डॉक्टर, समग्र थेरेपी और पंचकर्म।',
    card_fertility: 'प्रजनन क्षमता और आईवीएफ',
    card_fertility_desc: 'विशेषज्ञ आईवीएफ डॉक्टर, फर्टिलिटी परीक्षण और देखभाल।',
    card_health_insurance: 'स्वास्थ्य बीमा',
    card_insurance_desc: 'कैशलेस अस्पताल क्लेम और व्यापक कवरेज।',
    card_emergency: 'आपातकालीन एसओएस',
    card_emergency_desc: '24/7 एम्बुलेंस प्रेषण और आपातकालीन हेल्पलाइन।',
    specialties_heading: 'किसी भी स्वास्थ्य समस्या के लिए शीर्ष विशेषज्ञों से परामर्श लें',
    specialties_subtitle: '25+ विशेषज्ञताओं में सत्यापित डॉक्टरों के साथ निजी परामर्श',
    book_in_clinic: 'क्लीनिक अपॉइंटमेंट बुक करें',
    book_now: 'अभी बुक करें',
    order_now: 'अभी ऑर्डर करें',
    view_slots: 'स्लॉट देखें',
    view_details: 'विवरण देखें',
    consult_now: 'अभी परामर्श लें',
    add_to_cart: 'कार्ट में जोड़ें',
    apply: 'लागू करें',
    close: 'बंद करें',
    confirm: 'पुष्टि करें',
  },
  ta: {
    app_settings: 'செயலி அமைப்புகள்',
    settings_subtitle: 'விருப்பத்தேர்வுகள், பாதுகாப்பு & அமைப்பு',
    notifications_alerts: 'அறிவிப்புகள் & எச்சரிக்கைகள்',
    push_notifications: 'புஷ் அறிவிப்புகள்',
    push_sub: 'முன்பதிவு நினைவூட்டல்கள் & சுகாதார குறிப்புகள்',
    whatsapp_updates: 'வாட்ஸ்அப் மருந்துச்சீட்டு & ரசீதுகள்',
    whatsapp_sub: 'வாட்ஸ்அப்பில் ஆர்டர் விவரங்களைப் பெறுங்கள்',
    sms_alerts: 'SMS அறிவிப்புகள்',
    sms_sub: 'முக்கியமான OTP மற்றும் மருத்துவமனை உறுதிப்படுத்தல்கள்',
    security_auth: 'பாதுகாப்பு & அங்கீகாரம்',
    change_password: 'கடவுச்சொல்லை மாற்றவும்',
    change_pass_sub: 'உங்கள் உள்நுழைவு கடவுச்சொல்லை மாற்றவும்',
    biometric_unlock: 'பயோமெட்ரிக் & ஃபேஸ் அன்லாக்',
    biometric_sub: 'விரைவான பயோமெட்ரிக் அங்கீகாரம்',
    regional_display: 'பிராந்திய & காட்சி',
    app_language: 'செயலி மொழி',
    dark_mode: 'டார்க் மோட் தீம்',
    dark_mode_sub: 'லைட் மற்றும் டார்க் தீம்களுக்கு இடையே மாறவும்',
    data_storage: 'தரவு & சேமிப்பகம்',
    clear_cache: 'செயலி தற்காலிக சேமிப்பை அழிக்கவும்',
    clear_cache_sub: 'தற்காலிக கோப்புகளை நீக்கவும்',
    logout_btn: 'MediUnify இலிருந்து வெளியேறு',
    app_version: 'MediUnify ஹெல்த்கேர் • v2.4.0 (தமிழ்)',
    select_language: 'செயலி மொழியைத் தேர்ந்தெடுக்கவும்',
    cancel: 'ரத்துசெய்',
    save: 'சேமி',
    current_password: 'தற்போதைய கடவுச்சொல்',
    new_password: 'புதிய கடவுச்சொல்',
    confirm_password: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    update_password_btn: 'கடவுச்சொல்லைப் புதுப்பிக்கவும்',
    cache_cleared_title: 'தற்காலிக சேமிப்பு அழிக்கப்பட்டது!',
    cache_cleared_msg: 'தற்காலிக நினைவகம் வெற்றிகரமாக அழிக்கப்பட்டது.',
    lang_changed_msg: 'செயலி மொழி தமிழுக்கு மாற்றப்பட்டது',
    theme_switched_dark: 'டார்க் மோட் செயல்படுத்தப்பட்டது',
    theme_switched_light: 'லைட் மோட் செயல்படுத்தப்பட்டது',
    nav_home: 'முகப்பு',
    nav_search: 'தேடல்',
    nav_ai_bot: 'AI சாட்பாட்',
    nav_alerts: 'எச்சரிக்கைகள்',
    nav_history: 'வரலாறு',
    nav_find_doctors: 'மருத்துவர்களைக் கண்டறியவும்',
    nav_lab_tests: 'ஆய்வகப் பரிசோதனைகள்',
    nav_order_medicine: 'மருந்துகளை ஆர்டர் செய்யுங்கள்',
    nav_surgeries: 'அறுவை சிகிச்சைகள்',
    nav_scans_xray: 'ஸ்கேன் & எக்ஸ்-ரே',
    nav_more_services: 'கூடுதல் சேவைகள்',
    nav_login_signup: 'உள்நுழைவு / பதிவுசெய்க',
    nav_location: 'இருப்பிடம்',
    nav_select_location: 'உங்கள் இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
    nav_language: 'மொழி',
    nav_cart: 'கார்ட்',
    profile_title: 'சுயவிவரம்',
    guest_user: 'விருந்தினர் பயனர்',
    guest_subtitle: 'உங்கள் சுயவிவரத்தை அணுக உள்நுழையவும்',
    edit_profile: 'சுயவிவரத்தைத் திருத்து',
    quick_access: 'விரைவு அணுகல்',
    family_members: 'குடும்ப உறுப்பினர்கள்',
    health_records: 'சுகாதார பதிவுகள்',
    payment_history: 'கட்டண வரலாறு',
    settings: 'அமைப்புகள்',
    personal_info: 'தனிப்பட்ட தகவல்',
    address: 'முகவரி',
    membership: 'உறுப்பினர் சேர்க்கை',
    notifications: 'அறிவிப்புகள்',
    language: 'மொழி',
    help_support: 'உதவி & ஆதரவு',
    about_app: 'MediUnify பற்றி',
    login_sign_in: 'உள்நுழைக',
    logout: 'வெளியேறு',
    valid_until: 'செல்லுபடியாகும் காலம்',
    active: 'செயலில் உள்ளது',
    explore_plans: 'திட்டங்களை ஆராயுங்கள்',
    done: 'முடிந்தது',
    lang_updated_title: 'மொழி புதுப்பிக்கப்பட்டது',
    lang_updated_desc: 'செயலி மொழி அமைக்கப்பட்டது:',
    my_appointments: 'எனது முன்பதிவுகள்',
    my_tests: 'எனது பரிசோதனைகள்',
    my_medicine_orders: 'எனது மருந்து ஆர்டர்கள்',
    my_medical_records: 'எனது மருத்துவ பதிவுகள்',
    my_online_consultations: 'எனது ஆன்லைன் ஆலோசனைகள்',
    my_feedback: 'எனது கருத்துகள்',
    view_update_profile: 'சுயவிவரத்தைப் பார்க்கவும் / புதுப்பிக்கவும்',
    hero_badge: 'இந்தியா முழுவதும் நோயாளிகளால் நம்பப்படுகிறது',
    refer_earn: 'பரிந்துரைத்து ₹250 பெறுங்கள்',
    hero_title_navy: 'உங்கள் சுகாதாரம்.',
    hero_title_teal: 'ஒரு அறிவார்ந்த தளம்.',
    hero_subtitle: 'மருத்துவர்களைக் கண்டறிந்து, ஆய்வகப் பரிசோதனைகளை முன்பதிவு செய்து, மருந்துகளை ஆர்டர் செய்யுங்கள் — அனைத்தும் ஒரே இடத்தில்.',
    search_placeholder: 'மருத்துவர்கள், மருத்துவமனைகள், சோதனைகள், மருந்துகளைத் தேடுங்கள்...',
    search_btn: 'தேடு',
    popular_searches: 'பிரபலமானவை:',
    book_appointment: 'முன்பதிவு செய்க',
    order_medicine: 'மருந்துகளை ஆர்டர் செய்யுங்கள்',
    view_services: 'சேவைகளைப் பார்க்கவும்',
    card_video_consult: 'வீடியோ ஆலோசனை',
    card_video_desc: 'உங்கள் வீட்டிலிருந்தே நிபுணத்துவ மருத்துவர்களுடன் இணையுங்கள்.',
    card_find_doctors: 'உங்கள் அருகிலுள்ள மருத்துவர்களைக் கண்டறியவும்',
    card_doctors_desc: 'சரிபார்க்கப்பட்ட நிபுணர்களுடன் உறுதிப்படுத்தப்பட்ட மருத்துவமனை முன்பதிவுகள்.',
    card_order_medicines: 'மருந்துகளை ஆர்டர் செய்யுங்கள்',
    card_medicine_desc: 'உண்மையான மருந்துகள் விரைவாக உங்கள் வீட்டுக்கு விநியோகிக்கப்படும்.',
    card_lab_tests: 'ஆய்வகப் பரிசோதனைகள்',
    card_lab_desc: 'வீட்டிலிருந்தே மாதிரி சேகரிப்பு மற்றும் துல்லியமான டிஜிட்டல் அறிக்கைகள்.',
    card_surgeries: 'அறுவை சிகிச்சைகள்',
    card_surgeries_desc: 'அறுவை சிகிச்சைக்கு காப்பீட்டு உதவி மற்றும் பிரத்யேக பராமரிப்பு.',
    card_scans_xray: 'ஸ்கேன் & எக்ஸ்-ரே',
    card_scans_desc: 'சான்றளிக்கப்பட்ட ஆய்வகங்களில் துல்லியமான எம்ஆர்ஐ, சிடி மற்றும் எக்ஸ்-ரே.',
    card_home_nursing: 'ஹோம் நர்சிங் & பராமரிப்பு',
    card_nursing_desc: 'பயிற்சி பெற்ற செவிலியர்கள் உங்கள் வீட்டுக்கே வருவார்கள்.',
    card_equipment_rental: 'மருத்துவ உபகரண வாடகை',
    card_equipment_desc: 'மருத்துவமனை படுக்கைகள், ஆக்சிஜன் செறிவூட்டிகள், சக்கர நாற்காலிகள்.',
    card_ayurveda: 'ஆயுர்வேதம் & ஆரோக்கியம்',
    card_ayurveda_desc: 'பாரம்பரிய ஆயுர்வேத மருத்துவர்கள் மற்றும் பஞ்சகர்மா சிகிச்சை.',
    card_fertility: 'கருவுறுதல் & IVF',
    card_fertility_desc: 'சிறப்பு IVF மருத்துவர்கள் மற்றும் பரிசோதனைகள்.',
    card_health_insurance: 'மருத்துவக் காப்பீடு',
    card_insurance_desc: 'பணமில்லா மருத்துவமனை சிகிச்சைகள் & விரிவான பாதுகாப்பு.',
    card_emergency: 'அவசர SOS',
    card_emergency_desc: '24/7 ஆம்புலன்ஸ் சேவை மற்றும் அவசர உதவி எண்.',
    specialties_heading: 'எந்தவொரு சுகாதாரப் பிரச்சனைக்கும் சிறந்த நிபுணர்களை அணுகவும்',
    specialties_subtitle: '25+ சிறப்புப் பிரிவுகளில் சரிபார்க்கப்பட்ட மருத்துவர்களுடன் தனிப்பட்ட ஆலோசனை',
    book_in_clinic: 'மருத்துவமனை வருகையை முன்பதிவு செய்க',
    book_now: 'இப்போதே பதிவுசெய்க',
    order_now: 'இப்போதே ஆர்டர் செய்க',
    view_slots: 'நேரங்களை காண்க',
    view_details: 'விவரங்களை காண்க',
    consult_now: 'ஆலோசனை பெறுக',
    add_to_cart: 'கார்ட்டில் சேர்க்கவும்',
    apply: 'பயன்படுத்து',
    close: 'மூடு',
    confirm: 'உறுதிப்படுத்து',
  },
  te: {
    app_settings: 'యాప్ సెట్టింగ్స్',
    settings_subtitle: 'ప్రాధాన్యతలు, భద్రత & సిస్టమ్',
    notifications_alerts: 'నోటిఫికేషన్లు & హెచ్చరికలు',
    push_notifications: 'పుష్ నోటిఫికేషన్లు',
    push_sub: 'అపాయింట్‌మెంట్ రిమైండర్లు & ఆరోగ్య చిట్కాలు',
    whatsapp_updates: 'వాట్సాప్ ప్రిస్క్రిప్షన్ & బిల్లులు',
    whatsapp_sub: 'వాట్సాప్‌లో ఆర్డర్ ట్రాకింగ్ పొందండి',
    sms_alerts: 'SMS నోటిఫికేషన్లు',
    sms_sub: 'ముఖ్యమైన OTPలు మరియు ఆసుపత్రి నిర్ధారణలు',
    security_auth: 'భద్రత & ధృవీకరణ',
    change_password: 'పాస్‌వర్డ్ మార్చండి',
    change_pass_sub: 'ఖాతా లాగిన్ పాస్‌వర్డ్‌ను అప్‌డేట్ చేయండి',
    biometric_unlock: 'బయోమెట్రిక్ & ఫేస్ అన్‌లాక్',
    biometric_sub: 'వేగవంతమైన బయోమెట్రిక్ ప్రమాణీకరణ',
    regional_display: 'ప్రాంతీయ & ప్రదర్శన',
    app_language: 'యాప్ భాష',
    dark_mode: 'డార్క్ మోడ్ థీమ్',
    dark_mode_sub: 'లైట్ మరియు డార్క్ థీమ్‌ల మధ్య మారండి',
    data_storage: 'డేటా & నిల్వ',
    clear_cache: 'యాప్ కాష్ క్లియర్ చేయండి',
    clear_cache_sub: 'తాత్కాలిక కాష్ & చిత్రాలను తొలగించండి',
    logout_btn: 'MediUnify నుండి లాగౌట్ అవ్వండి',
    app_version: 'MediUnify హెల్త్‌కేర్ యాప్ • v2.4.0 (తెలుగు)',
    select_language: 'యాప్ భాషను ఎంచుకోండి',
    cancel: 'రద్దు చేయండి',
    save: 'సేవ్ చేయండి',
    current_password: 'ప్రస్తుత పాస్‌వర్డ్',
    new_password: 'కొత్త పాస్‌వర్డ్',
    confirm_password: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
    update_password_btn: 'పాస్‌వర్డ్ అప్‌డేట్ చేయండి',
    cache_cleared_title: 'కాష్ క్లియర్ చేయబడింది!',
    cache_cleared_msg: 'తాత్కాలిక మెమరీ విజయవంతంగా క్లియర్ చేయబడింది.',
    lang_changed_msg: 'యాప్ భాష తెలుగుగా నవీకరించబడింది',
    theme_switched_dark: 'డార్క్ మోడ్ ఆన్ చేయబడింది',
    theme_switched_light: 'లైట్ మోడ్ ఆన్ చేయబడింది',
    nav_home: 'హోమ్',
    nav_search: 'శోధన',
    nav_ai_bot: 'AI చాట్ బాట్',
    nav_alerts: 'హెచ్చరికలు',
    nav_history: 'చరిత్ర',
    nav_find_doctors: 'వైద్యులను కనుగొనండి',
    nav_lab_tests: 'ల్యాబ్ పరీక్షలు',
    nav_order_medicine: 'మందులు ఆర్డర్ చేయండి',
    nav_surgeries: 'శస్త్రచికిత్సలు',
    nav_scans_xray: 'స్కాన్లు & ఎక్స్-రే',
    nav_more_services: 'మరిన్ని సేవలు',
    nav_login_signup: 'లాగిన్ / సైన్ అప్',
    nav_location: 'ప్రాంతం',
    nav_select_location: 'మీ ప్రాంతాన్ని ఎంచుకోండి',
    nav_language: 'భాష',
    nav_cart: 'కార్ట్',
    profile_title: 'ప్రొఫైల్',
    guest_user: 'అతిథి వినియోగదారు',
    guest_subtitle: 'మీ ప్రొఫైల్ యాక్సెస్ చేయడానికి లాగిన్ అవ్వండి',
    edit_profile: 'ప్రొఫైల్ సవరించండి',
    quick_access: 'త్వరిత యాక్సెస్',
    family_members: 'కుటుంబ సభ్యులు',
    health_records: 'ఆరోగ్య రికార్డులు',
    payment_history: 'చెల్లింపు చరిత్ర',
    settings: 'సెట్టింగ్స్',
    personal_info: 'వ్యక్తిగత సమాచారం',
    address: 'చిరునామా',
    membership: 'సభ్యత్వం',
    notifications: 'నోటిఫికేషన్లు',
    language: 'భాష',
    help_support: 'సహాయం & మద్దతు',
    about_app: 'MediUnify గురించి',
    login_sign_in: 'లాగిన్ / సైన్ ఇన్',
    logout: 'లాగౌట్',
    valid_until: 'చెల్లుబాటు వ్యవధి',
    active: 'యాక్టివ్',
    explore_plans: 'ప్లాన్‌లను చూడండి',
    done: 'పూర్తయింది',
    lang_updated_title: 'భాష నవీకరించబడింది',
    lang_updated_desc: 'యాప్ భాష సెట్ చేయబడింది:',
    my_appointments: 'నా అపాయింట్‌మెంట్‌లు',
    my_tests: 'నా పరీక్షలు',
    my_medicine_orders: 'నా ఔషధ ఆర్డర్లు',
    my_medical_records: 'నా వైద్య రికార్డులు',
    my_online_consultations: 'నా ఆన్‌లైన్ సంప్రదింపులు',
    my_feedback: 'నా ఫీడ్‌బ్యాక్',
    view_update_profile: 'ప్రొఫైల్ చూడండి / అప్‌డేట్ చేయండి',
    hero_badge: 'భారతదేశ వ్యాప్తంగా రోగులచే విశ్వసించబడింది',
    refer_earn: 'రెఫర్ చేయండి ₹250 సంపాదించండి',
    hero_title_navy: 'మీ ఆరోగ్య సంరక్షణ.',
    hero_title_teal: 'ఒక తెలివైన ప్లాట్‌ఫారమ్.',
    hero_subtitle: 'వైద్యులను కనుగొనండి, ల్యాబ్ పరీక్షలను బుక్ చేయండి, మందులను ఆర్డర్ చేయండి — అన్నీ ఒకే చోట.',
    search_placeholder: 'వైద్యులు, క్లినిక్‌లు, ఆసుపత్రులు, పరీక్షలు, మందులను శోధించండి...',
    search_btn: 'శోధించండి',
    popular_searches: 'ప్రజాదరణ పొందినవి:',
    book_appointment: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    order_medicine: 'మందులు ఆర్డర్ చేయండి',
    view_services: 'సేవలను చూడండి',
    card_video_consult: 'వీడియో సంప్రదింపులు',
    card_video_desc: 'మీ ఇంటి నుండే నిపుణులైన వైద్యులతో మాట్లాడండి.',
    card_find_doctors: 'మీ సమీపంలోని వైద్యులను కనుగొనండి',
    card_doctors_desc: 'ధృవీకరించబడిన నిపుణులతో క్లినిక్ అపాయింట్‌మెంట్‌లు.',
    card_order_medicines: 'మందులు ఆర్డర్ చేయండి',
    card_medicine_desc: 'అసలైన మందులు వేగంగా మీ ఇంటికి డెలివరీ చేయబడతాయి.',
    card_lab_tests: 'ల్యాబ్ పరీక్షలు',
    card_lab_desc: 'ఇంటి వద్ద శాంపిల్ కలెక్షన్ మరియు ఖచ్చితమైన డిజిటల్ నివేదికలు.',
    card_surgeries: 'శస్త్రచికిత్సలు',
    card_surgeries_desc: 'శస్త్రచికిత్సకు బీమా సహాయం మరియు వ్యక్తిగత సంరక్షణ.',
    card_scans_xray: 'స్కాన్లు & ఎక్స్-రే',
    card_scans_desc: 'ధృవీకరించబడిన ల్యాబ్‌లలో ఎంఆర్‌ఐ, సిటి మరియు ఎక్స్-రే స్కాన్‌లు.',
    card_home_nursing: 'హోమ్ నర్సింగ్ & సంరక్షణ',
    card_nursing_desc: 'శిక్షణ పొందిన నర్సులు మరియు సంరక్షకులు మీ ఇంటి వద్దకే.',
    card_equipment_rental: 'పరికరాల అద్దె',
    card_equipment_desc: 'హాస్పిటల్ బెడ్స్, ఆక్సిజన్ కాన్సంట్రేటర్లు, వీల్ చైర్లు.',
    card_ayurveda: 'ఆయుర్వేదం & వెల్‌నెస్',
    card_ayurveda_desc: 'సాంప్రదాయ ఆయుర్వేద వైద్యులు మరియు పంచకర్మ చికిత్స.',
    card_fertility: 'సంతానోత్పత్తి & IVF',
    card_fertility_desc: 'ప్రత్యేక IVF వైద్యులు మరియు సంతానోత్పత్తి పరీక్షలు.',
    card_health_insurance: 'ఆరోగ్య బీమా',
    card_insurance_desc: 'క్యాష్‌లెస్‌ ఆసుపత్రి క్లెయిమ్‌లు మరియు సమగ్ర రక్షణ.',
    card_emergency: 'అత్యవసర SOS',
    card_emergency_desc: '24/7 అంబులెన్స్ డిస్పాచ్ మరియు అత్యవసర హెల్ప్‌లైన్.',
    specialties_heading: 'ఏదైనా ఆరోగ్య సమస్య కోసం ప్రముఖ నిపుణులను సంప్రదించండి',
    specialties_subtitle: '25+ విభాగాలలో ధృవీకరించబడిన వైద్యులతో వ్యక్తిగత సంప్రదింపులు',
    book_in_clinic: 'క్లినిక్ విజిట్ బుక్ చేయండి',
    book_now: 'ఇప్పుడే బుక్ చేయండి',
    order_now: 'ఇప్పుడే ఆర్డర్ చేయండి',
    view_slots: 'స్లాట్‌లను చూడండి',
    view_details: 'వివరాలు చూడండి',
    consult_now: 'ఇప్పుడే సంప్రదించండి',
    add_to_cart: 'కార్ట్‌కు జోడించండి',
    apply: 'వర్తించు',
    close: 'మూసివేయి',
    confirm: 'నిర్ధారించండి',
  },
  ml: {
    app_settings: 'ആപ്പ് ക്രമീകരണങ്ങൾ',
    settings_subtitle: 'മുൻഗണനകൾ, സുരക്ഷ, സിസ്റ്റം',
    notifications_alerts: 'അറിയിപ്പുകൾ & അലേർട്ടുകൾ',
    push_notifications: 'പുഷ് അറിയിപ്പുകൾ',
    push_sub: 'അപ്പോയിന്റ്മെന്റ് ഓർമ്മപ്പെടുത്തലുകളും ആരോഗ്യ ടിപ്പുകളും',
    whatsapp_updates: 'വാട്ട്സ്ആപ്പ് കുറിപ്പടിയും ബില്ലുകളും',
    whatsapp_sub: 'വാട്ട്സ്ആപ്പിൽ ഓർഡർ ട്രാക്കിംഗ് നേടുക',
    sms_alerts: 'എസ്എംഎസ് അറിയിപ്പുകൾ',
    sms_sub: 'പ്രധാന ഒടിപികളും ആശുപത്രി സ്ഥിരീകരണങ്ങളും',
    security_auth: 'സുരക്ഷ & പ്രാമാണീകരണം',
    change_password: 'പാസ്‌വേഡ് മാറ്റുക',
    change_pass_sub: 'നിങ്ങളുടെ ലോഗിൻ പാസ്‌വേഡ് അപ്‌ഡേറ്റ് ചെയ്യുക',
    biometric_unlock: 'ബയോമെട്രിക് & ഫെയ്സ് അൺലോക്ക്',
    biometric_sub: 'വേഗത്തിലുള്ള ബയോമെട്രിക് പ്രാമാണീകരണം',
    regional_display: 'പ്രാദേശിക & ഡിസ്പ്ലേ',
    app_language: 'ആപ്പ് ഭാഷ',
    dark_mode: 'ഡാർക്ക് മോഡ് തീം',
    dark_mode_sub: 'ലൈറ്റ്, ഡാർക്ക് തീമുകൾക്കിടയിൽ മാറുക',
    data_storage: 'ഡാറ്റ & സംഭരണം',
    clear_cache: 'ആപ്പ് കാഷെ മായ്ക്കുക',
    clear_cache_sub: 'താത്കാലിക കാഷെയും ചിത്രങ്ങളും മായ്ക്കുക',
    logout_btn: 'MediUnify-ൽ നിന്ന് ലോഗൗട്ട് ചെയ്യുക',
    app_version: 'MediUnify ഹെൽത്ത്കെയർ • v2.4.0 (മലയാളം)',
    select_language: 'ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക',
    cancel: 'റദ്ദാക്കുക',
    save: 'സംരക്ഷിക്കുക',
    current_password: 'നിലവിലെ പാസ്‌വേഡ്',
    new_password: 'പുതിയ പാസ്‌വേഡ്',
    confirm_password: 'പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    update_password_btn: 'പാസ്‌വേഡ് അപ്‌ഡേറ്റ് ചെയ്യുക',
    cache_cleared_title: 'കാഷെ മായ്ച്ചു!',
    cache_cleared_msg: 'താത്കാലിക മെമ്മറി വിജയകരമായി മായ്ച്ചു.',
    lang_changed_msg: 'ആപ്പ് ഭാഷ മലയാളത്തിലേക്ക് മാറ്റി',
    theme_switched_dark: 'ഡാർക്ക് മോഡ് സജീവമാക്കി',
    theme_switched_light: 'ലൈറ്റ് മോഡ് സജീവമാക്കി',
    nav_home: 'ഹോം',
    nav_search: 'തിരയുക',
    nav_ai_bot: 'AI ചാറ്റ് ബോട്ട്',
    nav_alerts: 'അലേർട്ടുകൾ',
    nav_history: 'ചരിത്രം',
    nav_find_doctors: 'ഡോക്ടർമാരെ കണ്ടെത്തുക',
    nav_lab_tests: 'ലാബ് പരിശോധനകൾ',
    nav_order_medicine: 'മരുന്നുകൾ ഓർഡർ ചെയ്യുക',
    nav_surgeries: 'ശസ്ത്രക്രിയകൾ',
    nav_scans_xray: 'സ്കാനുകളും എക്സ്-റേയും',
    nav_more_services: 'കൂടുതൽ സേവനങ്ങൾ',
    nav_login_signup: 'ലോഗിൻ / സൈൻ അപ്പ്',
    nav_location: 'സ്ഥലം',
    nav_select_location: 'നിങ്ങളുടെ സ്ഥലം തിരഞ്ഞെടുക്കുക',
    nav_language: 'ഭാഷ',
    nav_cart: 'കാർട്ട്',
    profile_title: 'പ്രൊഫൈൽ',
    guest_user: 'അതിഥി ഉപയോക്താവ്',
    guest_subtitle: 'പ്രൊഫൈൽ കാണാൻ ലോഗിൻ ചെയ്യുക',
    edit_profile: 'പ്രൊഫൈൽ തിരുത്തുക',
    quick_access: 'ദ്രുത പ്രവേശനം',
    family_members: 'കുടുംബാംഗങ്ങൾ',
    health_records: 'ആരോഗ്യ രേഖകൾ',
    payment_history: 'പേയ്‌മെന്റ് ചരിത്രം',
    settings: 'ക്രമീകരണങ്ങൾ',
    personal_info: 'വ്യക്തിഗത വിവരങ്ങൾ',
    address: 'വിലാസം',
    membership: 'അംഗത്വം',
    notifications: 'അറിയിപ്പുകൾ',
    language: 'ഭാഷ',
    help_support: 'സഹായവും പിന്തുണയും',
    about_app: 'MediUnify കുറിച്ച്',
    login_sign_in: 'ലോഗിൻ ചെയ്യുക',
    logout: 'ലോഗൗട്ട്',
    valid_until: 'കാലാവധി',
    active: 'സജീവം',
    explore_plans: 'പ്ലാനുകൾ കാണുക',
    done: 'പൂർത്തിയായി',
    lang_updated_title: 'ഭാഷ അപ്‌ഡേറ്റ് ചെയ്തു',
    lang_updated_desc: 'ആപ്പ് ഭാഷ സജ്ജീകരിച്ചു:',
    my_appointments: 'എന്റെ അപ്പോയിന്റ്മെന്റുകൾ',
    my_tests: 'എന്റെ ടെസ്റ്റുകൾ',
    my_medicine_orders: 'എന്റെ മരുന്ന് ഓർഡറുകൾ',
    my_medical_records: 'എന്റെ മെഡിക്കൽ രേഖകൾ',
    my_online_consultations: 'എന്റെ ഓൺലൈൻ കൺസൾട്ടേഷനുകൾ',
    my_feedback: 'എന്റെ പ്രതികരണം',
    view_update_profile: 'പ്രൊഫൈൽ കാണുക / പുതുക്കുക',
    hero_badge: 'ഇന്ത്യയിലുടനീളമുള്ള രോഗികൾ വിശ്വസിക്കുന്നു',
    refer_earn: 'റഫർ ചെയ്ത് ₹250 നേടൂ',
    hero_title_navy: 'നിങ്ങളുടെ ആരോഗ്യ പരിചരണം.',
    hero_title_teal: 'ഒരു സ്മാർട്ട് പ്ലാറ്റ്‌ഫോം.',
    hero_subtitle: 'ഡോക്ടർമാരെ കണ്ടെത്തുക, ലാബ് ടെസ്റ്റുകൾ ബുക്ക് ചെയ്യുക, മരുന്നുകൾ ഓർഡർ ചെയ്യുക — എല്ലാം ഒരിടത്ത്.',
    search_placeholder: 'ഡോക്ടർമാർ, ക്ലിനിക്കുകൾ, ആശുപത്രികൾ, മരുന്നുകൾ എന്നിവ തിരയുക...',
    search_btn: 'തിരയുക',
    popular_searches: 'ജനപ്രിയം:',
    book_appointment: 'അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക',
    order_medicine: 'മരുന്നുകൾ ഓർഡർ ചെയ്യുക',
    view_services: 'സേവനങ്ങൾ കാണുക',
    card_video_consult: 'വീഡിയോ കൺസൾട്ടേഷൻ',
    card_video_desc: 'വീട്ടിലിരുന്ന് വിദഗ്ധ ഡോക്ടർമാരുമായി ബന്ധപ്പെടുക.',
    card_find_doctors: 'അടുത്തുള്ള ഡോക്ടർമാരെ കണ്ടെത്തുക',
    card_doctors_desc: 'വിദഗ്ധരുമായി ഉറപ്പായ ക്ലിനിക്ക് അപ്പോയിന്റ്മെന്റുകൾ.',
    card_order_medicines: 'മരുന്നുകൾ ഓർഡർ ചെയ്യുക',
    card_medicine_desc: 'യഥാർത്ഥ മരുന്നുകൾ വേഗത്തിൽ വീട്ടിലെത്തുന്നു.',
    card_lab_tests: 'ലാബ് പരിശോധനകൾ',
    card_lab_desc: 'വീട്ടിൽ നിന്ന് സാമ്പിൾ ശേഖരണവും കൃത്യമായ ഡിജിറ്റൽ റിപ്പോർട്ടുകളും.',
    card_surgeries: 'ശസ്ത്രക്രിയകൾ',
    card_surgeries_desc: 'സർജറിക്ക് ഇൻഷുറൻസ് സഹായവും പരിചരണവും.',
    card_scans_xray: 'സ്കാനുകളും എക്സ്-റേയും',
    card_scans_desc: 'എംആർഐ, സിടി, അൾട്രാസൗണ്ട്, എക്സ്-റേ പരിശോധനകൾ.',
    card_home_nursing: 'ഹോം നഴ്സിംഗും പരിചരണവും',
    card_nursing_desc: 'പരിശീലനം ലഭിച്ച നഴ്സുമാർ നിങ്ങളുടെ വീട്ടിലെത്തുന്നു.',
    card_equipment_rental: 'ഉപകരണ വാടക',
    card_equipment_desc: 'ഹോസ്പിറ്റൽ ബെഡുകൾ, ഓക്സിജൻ കോൺസൻട്രേറ്ററുകൾ, വീൽചെയറുകൾ.',
    card_ayurveda: 'ആയുർവേദവും വെൽനസും',
    card_ayurveda_desc: 'പരമ്പരാഗത ആയുർവേദ ഡോക്ടർമാരും പഞ്ചകർമ്മ ചികിത്സയും.',
    card_fertility: 'ഫെർട്ടിലിറ്റിയും IVF-ഉം',
    card_fertility_desc: 'പ്രത്യേക IVF ഡോക്ടർമാരും ഫെർട്ടിലിറ്റി പരിശോധനകളും.',
    card_health_insurance: 'ആരോഗ്യ ഇൻഷുറൻസ്',
    card_insurance_desc: 'ക്യാഷ്‌ലെസ് ആശുപത്രി ക്ലെയിമുകളും സമഗ്ര കവറേജും.',
    card_emergency: 'അടിയന്തര SOS',
    card_emergency_desc: '24/7 ആംബുലൻസ് ഡിസ്പാച്ചും ഹെൽപ്പ്‌ലൈനും.',
    specialties_heading: 'ഏതൊരു ആരോഗ്യ പ്രശ്നത്തിനും മികച്ച വിദഗ്ധരെ സമീപിക്കുക',
    specialties_subtitle: '25+ സ്പെഷ്യാലിറ്റികളിലെ ഡോക്ടർമാരുമായി സ്വകാര്യ കൺസൾട്ടേഷൻ',
    book_in_clinic: 'ക്ലിനിക്ക് സന്ദർശനം ബുക്ക് ചെയ്യുക',
    book_now: 'ഇപ്പോൾ ബുക്ക് ചെയ്യുക',
    order_now: 'ഇപ്പോൾ ഓർഡർ ചെയ്യുക',
    view_slots: 'സ്ലോട്ടുകൾ കാണുക',
    view_details: 'വിശദാംശങ്ങൾ കാണുക',
    consult_now: 'ഇപ്പോൾ സംസാരിക്കുക',
    add_to_cart: 'കാർട്ടിൽ ചേർക്കുക',
    apply: 'ബാധകമാക്കുക',
    close: 'അടയ്ക്കുക',
    confirm: 'സ്ഥിരീകരിക്കുക',
  },
};

const ThemeContext = createContext();

export const ThemeProvider = ({ children }) => {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [language, setLanguage] = useState('en');
  const [notifications, setNotifications] = useState({
    push: true,
    whatsapp: true,
    sms: true,
  });
  const [biometricEnabled, setBiometricEnabled] = useState(true);

  // Load preferences from storage on mount
  useEffect(() => {
    loadSettings();
  }, []);

  const loadSettings = async () => {
    try {
      const savedDark = await AsyncStorage.getItem('@unnathi_dark_mode');
      if (savedDark !== null) {
        setIsDarkMode(savedDark === 'true');
      }

      let savedLang = await AsyncStorage.getItem('@unnathi_app_language');
      if (!savedLang && Platform.OS === 'web' && typeof localStorage !== 'undefined') {
        savedLang = localStorage.getItem('@unnathi_app_language');
      }
      if (savedLang) {
        setLanguage(savedLang);
      }

      const savedNotifs = await AsyncStorage.getItem('@unnathi_notification_settings');
      if (savedNotifs) {
        setNotifications(JSON.parse(savedNotifs));
      }

      const savedBio = await AsyncStorage.getItem('@unnathi_biometric_enabled');
      if (savedBio !== null) {
        setBiometricEnabled(savedBio === 'true');
      }
    } catch (e) {
      console.log('Error loading settings from storage:', e);
    }
  };

  const toggleDarkMode = async (value) => {
    try {
      setIsDarkMode(value);
      await AsyncStorage.setItem('@unnathi_dark_mode', value ? 'true' : 'false');
    } catch (e) {
      console.log('Error saving dark mode:', e);
    }
  };

  const changeLanguage = async (langCode) => {
    try {
      setLanguage(langCode);
      await AsyncStorage.setItem('@unnathi_app_language', langCode);
      if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
        try {
          localStorage.setItem('@unnathi_app_language', langCode);
          window.dispatchEvent(new CustomEvent('app-language-changed', { detail: langCode }));
        } catch (e) {}
      }
    } catch (e) {
      console.log('Error saving language:', e);
    }
  };

  const updateNotifications = async (key, val) => {
    try {
      const updated = { ...notifications, [key]: val };
      setNotifications(updated);
      await AsyncStorage.setItem('@unnathi_notification_settings', JSON.stringify(updated));
    } catch (e) {
      console.log('Error saving notification settings:', e);
    }
  };

  const toggleBiometric = async (val) => {
    try {
      setBiometricEnabled(val);
      await AsyncStorage.setItem('@unnathi_biometric_enabled', val ? 'true' : 'false');
    } catch (e) {
      console.log('Error saving biometric settings:', e);
    }
  };

  // Translation helper function
  const t = (key, fallback) => {
    const langObj = TRANSLATIONS[language] || TRANSLATIONS.en;
    return langObj?.[key] || TRANSLATIONS.en?.[key] || fallback || key;
  };

  // Adaptive Typography & Layout system (Section 17A)
  const isIndic = ['kn', 'hi', 'ta', 'te', 'ml'].includes(language);
  const isNonEnglish = language !== 'en';

  const getAdaptiveFontSize = (baseSize, options = {}) => {
    if (!isIndic) return baseSize;
    const minSize = options.minSize ?? (baseSize > 14 ? baseSize - 1.5 : baseSize - 1);
    if (options.compact) {
      return Math.max(minSize, baseSize - (options.scaleDown || 1));
    }
    return baseSize;
  };

  const getAdaptiveLineHeight = (fontSize, customLineHeight) => {
    if (!isIndic) return customLineHeight || Math.round(fontSize * 1.3);
    const minLineHeight = Math.round(fontSize * 1.38);
    return customLineHeight ? Math.max(customLineHeight, minLineHeight) : minLineHeight;
  };

  const adaptiveTextStyle = (baseStyle = {}, options = {}) => {
    const rawSize = baseStyle.fontSize || 14;
    const adaptedSize = getAdaptiveFontSize(rawSize, options);
    const adaptedLineHeight = getAdaptiveLineHeight(adaptedSize, baseStyle.lineHeight);
    return {
      ...baseStyle,
      fontSize: adaptedSize,
      lineHeight: adaptedLineHeight,
    };
  };

  // Dynamic Theme Palette
  const theme = {
    isDark: isDarkMode,
    background: isDarkMode ? '#0B1120' : '#FAFCFD',
    card: isDarkMode ? '#1E293B' : '#FFFFFF',
    cardSubtle: isDarkMode ? '#172554' : '#F0F9FF',
    headerBg: isDarkMode ? '#0F172A' : '#FFFFFF',
    text: isDarkMode ? '#F8FAFC' : '#1E3A8A',
    textSecondary: isDarkMode ? '#94A3B8' : '#64748B',
    border: isDarkMode ? '#334155' : '#DCE7EC',
    divider: isDarkMode ? '#1E293B' : '#F1F8FB',
    inputBg: isDarkMode ? '#0F172A' : '#FAFCFD',
    primary: '#00B894',
    teal: '#00B894',
    navyBlue: isDarkMode ? '#60A5FA' : '#1E3A8A',
    aqua: '#00C2CB',
    freshGreen: '#7BC96F',
    coral: '#FF7F50',
    slate: '#64748B',
    modalBg: isDarkMode ? '#1E293B' : '#FFFFFF',
    statusBar: isDarkMode ? 'light-content' : 'dark-content',
  };

  return (
    <ThemeContext.Provider
      value={{
        isDarkMode,
        toggleDarkMode,
        language,
        changeLanguage,
        isIndic,
        isNonEnglish,
        getAdaptiveFontSize,
        getAdaptiveLineHeight,
        adaptiveTextStyle,
        t,
        notifications,
        updateNotifications,
        biometricEnabled,
        toggleBiometric,
        theme,
        LANGUAGES,
      }}
    >
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    return {
      isDarkMode: false,
      toggleDarkMode: () => {},
      language: 'en',
      changeLanguage: () => {},
      isIndic: false,
      isNonEnglish: false,
      getAdaptiveFontSize: (s) => s,
      getAdaptiveLineHeight: (s, l) => l || Math.round(s * 1.3),
      adaptiveTextStyle: (s) => s,
      t: (k, fb) => fb || k,
      notifications: { push: true, whatsapp: true, sms: true },
      updateNotifications: () => {},
      biometricEnabled: true,
      toggleBiometric: () => {},
      theme: {
        isDark: false,
        background: '#FAFCFD',
        card: '#FFFFFF',
        text: '#1E3A8A',
        primary: '#00B894',
        border: '#DCE7EC',
      },
      LANGUAGES,
    };
  }
  return context;
};

export default ThemeContext;
